### PR TITLE
Fix `UseTweaksValues` type

### PR DESCRIPTION
**Pull request by ivanross**
This pr is meant to solve the issue described in #38. 

`any` is produced by `Leaves` because it has circular reference and it is generic (and has some `//@ts-ignore` too). 
Now it is lazily evaluated so typescript doesn't complain about its recursivity.

I also removed `Prev` type and `D` type parameter because  it seems to be unnecessary.

### CODE REVIEW

**Comment by dbismut** [comment]
This makes me realise how little I know about TypeScript. @ivanross it would be cool if you had the time to discuss about some types on another similar project that we're setting up with GM. @gsimone do you think we could grant Ivan access to controls?

**Review by dbismut — APPROVED** [review]

**Comment by dbismut** [comment]
@gsimone I'll let you submit the new version on npm?

**Comment by ivanross** [comment]
@dbismut Sure, I will be happy to help!

**Comment by gsimone** [comment]
@ivanross Sending you an invite right now! 👍

**Comment by gsimone** [comment]
v0.3.1 published 👍

**Comment by ivanross** [comment]
@gsimone invite received 👍

**Comment by unphased** [comment]
Hi @ivanross I've tested 0.3.0 and 0.3.1, and it seems that https://github.com/pmndrs/use-tweaks/issues/43 is caused by this change. 

Unfortunately I do not understand the code. Could you try to explain what changed? As far as I can tell on 0.3.0 the behavior is correct. It will produce a type that matches the type you specify. In 0.3.1, the type given is `{ "": <the type>}` instead.

**Comment by dbismut** [comment]
@ivanross if you're still handling this, have a look at: https://github.com/pmndrs/leva/blob/bbbb3f9f33f576491543fb077d6b9c120737b710/packages/leva/src/types/public-types.ts#L152

@unphased you may want to try https://github.com/pmndrs/leva/ instead of use-tweaks. The API is still moving but it should be easy to switch to it.

**Comment by unphased** [comment]
@dbismut Thank you for the link! Very helpful. I will evaluate.

**Comment by unphased** [comment]
I'm now finding that 0.3.0 still suffers from this problem, so the type issue appears to be from a peer dependency. Unfortunately. Will post back if I find out what it is.

**Comment by dbismut** [comment]
Hey, I'm afraid use-tweaks won't be under active development now that Leva is getting traction. Did you try it yet?

**Comment by unphased** [comment]
Yep I am aware, yeah sorry I didnt have time to delve into it. when i tried it in my project I got very mysterious type errors. It may be better now, since we are on react 17 now... but I've built some hooks off of use-tweaks by now so i'll have to revisit in just some weeks or months.

**Pull request merged**
